function(print_variables)
  message(STATUS "${PROJECT_NAME}") 
  message(STATUS "${PROJECT_VERSION}") 
  message(STATUS "${PROJECT_SOURCE_DIR}")
  message(STATUS "${PROJECT_BINARY_DIR}")
  message(STATUS "${CMAKE_SOURCE_DIR}")
  message(STATUS "${CMAKE_BINARY_DIR}")
  message(STATUS "${CMAKE_CURRENT_SOURCE_DIR}")
  message(STATUS "${CMAKE_CURRENT_BINARY_DIR}")
  message(STATUS "${CMAKE_CURRENT_LIST_FILE}")
  message(STATUS "${CMAKE_CURRENT_LIST_DIR}")
endfunction()